# Generated by Django 3.0.8 on 2020-09-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCatagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_catagories', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=50)),
                ('job_type', models.CharField(choices=[('full time', 'full time'), ('contract', 'contract'), ('part time', 'part time'), ('freelancer', 'freelancer'), ('internship', 'internship')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(default='Addis Ababa', max_length=30)),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(help_text='help')),
                ('experience_level', models.CharField(choices=[('senior', 'senior'), ('junior', 'junior'), ('manager', 'manager')], max_length=10)),
                ('Job_description', models.TextField()),
                ('JobCatagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobCatagories')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer')),
            ],
        ),
    ]
